# Generated by Django 5.0.7 on 2026-06-12 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchreport', '0002_matchreport_club'),
        ('players', '0004_alter_player_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=50)),
                ('for_us', models.BooleanField(default=True)),
                ('card_type', models.CharField(blank=True, choices=[('yellow', 'Gelb'), ('yellow_red', 'Gelb-Rot'), ('red', 'Rot')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matchreport.matchreport')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player')),
            ],
        ),
    ]
