# Generated by Django 5.0.7 on 2026-06-24 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('trainingsart', models.CharField(blank=True, choices=[('klassisch', 'Klassisches Training'), ('frei', 'Freies Training')], max_length=10)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('trainingstyp', models.CharField(choices=[('aktivierung', 'Aktivierung/Erwärmung'), ('spielform_1', 'Spielform_1'), ('zwischenblock', 'Zwischenblock'), ('spielform_2', 'Spielform_2')], max_length=20)),
                ('reihenfolge', models.IntegerField(default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='training.training')),
            ],
        ),
    ]
