# Generated by Django 5.0.7 on 2026-06-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingsblock",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainingsblock",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
