# Generated by Django 6.0.7 on 2026-07-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0004_seed_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="uebung",
            name="pictures",
            field=models.ImageField(
                blank=True, null=True, upload_to="uebungen/aufbau/"
            ),
        ),
    ]
