# Generated by Django 5.0.7 on 2026-07-12 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
        ("players", "0006_add_gk_attributes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taktik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario", models.CharField(max_length=100)),
                ("slot_number", models.IntegerField()),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("absichern", "Absichern"),
                            ("strafraum", "Strafraum"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="players.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clubs.club"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="taktik",
            constraint=models.UniqueConstraint(
                fields=("team", "scenario", "slot_number"), name="unique_slot_per_team"
            ),
        ),
    ]
