# Generated by Django 5.0.7 on 2026-06-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attr_ausdauer',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='attr_ballkontrolle',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='attr_dribbling',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='attr_einsatz',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='attr_entscheidung',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='attr_konzentration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='attr_kraft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='attr_passspiel',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='attr_schnelligkeit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='attr_schuss',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='attr_teamwork',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='attr_zweikampfstaerke',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
